# Configuration file for the project
app:
  name: "My Express App"
  environment: "production"
  version: "1.0.0"

database:
  host: "localhost"
  port: 5432
  username: "dbuser"
  password: "dbpassword"
  owner:"Thavasumoorthi"

server:
  port: 3000
